spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AQCyc9DER4EvKODRoXMIsjIf/n1U1oStEWUV5rYw6S1g3Ap4iZyQGf0bY30N+5u1MbfLevVICEDaL3wZIHND/LJkxHxMdJKm5MlrZddnOP1NrZIjqdmrMvmeqw/pQ06GZBhdgBrQ7j0V+gc7Afv6JiAgWReJZM517EWrNhM04yWHDy3eg9xxMtfxTNOErH9FrsDRJsl3jp+sfIRs9vs4dD5qqL1yr+TeqxEiWTFRltfomxJzJR8psieXpqDKurXqQYyslPUL0ZBjxqYngnSRHapAMZzOJdd5vr5QtIAmWpHwofIs59eq4QnZwzyKtGiyI/mApxu1294m5fm/l0ySBauVwQ52RNBpljsjp77+ViAY7kDTVnKUIkj1tpT4uIUhOpw= '

jwt:
  expiration_time: 86400000 
  secret: {cipher}AQALs6MT27BkUdLZQtE+aHBM2CZoM+mIACbgRt2RFdTdlukpQwHh4cfTcjBp9lbN7dSIl6Jr1l9BG5YSL+YkiAWEdjMLmEUG1XLNQznkZcr6Vc93jNnBDCkUNyPPpMC2bYkbr84eh+EZNrY4SVn5c0WKUDBJlJq3+763xUc9gmkgQZG25ZakAawX5QWt7iUycg2D4LmNoAB+fcOZH2S6VxhEGfj7J20Yl4XrvKlVhjhLeRW+PP2/o6827rJIHc95rQ/ZqmKuImXYNVnrTVPj2t8A2RK2ng3NK89gMTQKd7IwYF8OHVnsZa0pxYqexjeDS3/ucTWQ7GLpk1Hsx7P+s0BquStjCFO4K3WazHX468jzec0XNr+7ILhJMGgmtKiaWe72O1fqXnGkINF3GuhmjFxw4SkXg3SnK42d0R6sPP/eDNgVgVgwcKznVEyQEfcomCNgaNXllOVerPPlukl1CT/wHLy8M/YJV8HZT1JvqEAAu9DRklWccs8uJ0vpunoRZRwy5mxEZDFumrWS/uiX2if9bn/mnPL/4dh8FC6VXsmAHQ==

gateway:
  ip: 192.168.56.1 

order_service:
  url: http://127.0.0.1:8000/order-service/%s/orders