spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AQCyc9DER4EvKODRoXMIsjIf/n1U1oStEWUV5rYw6S1g3Ap4iZyQGf0bY30N+5u1MbfLevVICEDaL3wZIHND/LJkxHxMdJKm5MlrZddnOP1NrZIjqdmrMvmeqw/pQ06GZBhdgBrQ7j0V+gc7Afv6JiAgWReJZM517EWrNhM04yWHDy3eg9xxMtfxTNOErH9FrsDRJsl3jp+sfIRs9vs4dD5qqL1yr+TeqxEiWTFRltfomxJzJR8psieXpqDKurXqQYyslPUL0ZBjxqYngnSRHapAMZzOJdd5vr5QtIAmWpHwofIs59eq4QnZwzyKtGiyI/mApxu1294m5fm/l0ySBauVwQ52RNBpljsjp77+ViAY7kDTVnKUIkj1tpT4uIUhOpw='

jwt:
  expiration_time: 86400000 
  secret: changed-apigateway-default-dksgdjsbnvkjsdbkvjdbkvjbasjlcnaskvndjfbdkvbalnaslkbnsjbasdkasndlkasndalkjsdbvlsdnvlksdnvlkbsjdvbkjsdbvd

gateway:
  ip: 192.168.56.1 