server:
  port: 8888
spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JinHxxxxKim/SpringCloud-MSA.git
#          uri: file://C:\Users\JinHxxxxKim\inflearn\springcloud\git-local-repo
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httpexchanges, busrefresh
